services:
  - type: static
    name: lite-fitness
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - source: /*
        destination: /index.html
        type: rewrite
